### ISSUE TITLE
Error with Ubuntu 15.04

### ISSUE THREAD

**Issue by jamiehannaford** [rack-roles/cloud-monitoring-agent#12]
When the role runs on an Ubuntu 15.04 instance, this error is thrown:

> TASK: [cloud-monitoring-agent | Ubuntu | setup monitoring agent apt repository] ***
failed: [test32-as330ebcdb] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1431167079.28-170945286465477/apt_repository", line 2529, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1431167079.28-170945286465477/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/Vervet)-x86_64/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/cloudmonitoring/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/main/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/Vervet)-x86_64/binary-i386/Packages  404  Not Found
, W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/cloudmonitoring/binary-i386/Packages  404  Not Found
, W:Failed to fetch http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04/dists/(Vivid/main/binary-i386/Packages  404  Not Found

Is [this line](https://github.com/rack-roles/cloud-monitoring-agent/blob/master/tasks/Debian.yml#L10) correct? It doesn't seem to be populating the URL properly. It needs to be:

> http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-15.04-x86_64/dists/cloudmonitoring/main/binary-amd64/

**Comment by Linuturk** [comment]
Looks like something might have changed with those ansible facts. I'll have to dig into this more. You are on the right track if you want to submit a PR with the fix.

**Comment by rphillips** [comment]
I'm using ansible 1.9.1 and it seems to work ok.

**Comment by Linuturk** [comment]
@jamiehannaford Can you confirm your Ansible versions?

**Comment by jamiehannaford** [comment]
@Linuturk yep, that seemed to fix it.
