### ISSUE TITLE
Role hangs

### ISSUE THREAD

**Issue by linusnorton** [rack-roles/cloud-monitoring-agent#13]
I'm not sure of the cause but the role hangs for me. If I log into the server to see what it is doing it is running:

`rackspace-monitoring-agent --setup --username linusnorton --apikey ...`

I'm not sure how long it is supposed to take but I've left this for 30 minutes before killing it. It is reproducible with a clean server.

Running the command on the server shows that it is waiting for some input:

```
Please select the Entity that corresponds to this server:
  1. nt-production1 - enrYG4HPPp
       private0_v4: x
       access_ip1_v4: x
       public1_v4: x
       access_ip0_v6: x
       public0_v6: x
  2. Create a new Entity for this server (Entities can be viewed within Rackspace Intelligence - https://intelligence.rackspace.com)
```

Maybe the setup command should be run with the `-A` option?

**Comment by Linuturk** [comment]
I just updated with a -A on the command. Can you give it a shot and report back?

**Comment by linusnorton** [comment]
That seems to do the trick. Thanks
